#!/usr/bin/env python3
import argparse
import secrets
import sys

# Import our database context and models from the existing app
from main import SessionLocal, Merchant

def generate_api_key(prefix="sole_"):
    """
    Generates a cryptographically secure 32-byte API key.
    Format: sole_<64_hex_chars>
    """
    # 32 bytes of randomness equals 64 hex characters
    random_hex = secrets.token_hex(32)
    return f"{prefix}{random_hex}"

def create_merchant(name: str, wallet_address: str):
    """
    Creates a new Merchant in the SQLite database and outputs the credentials.
    """
    # Generate the credentials
    new_api_key = generate_api_key()
    
    # Open DB session
    db = SessionLocal()
    
    try:
        # Create merchant object (the 'id' UUID is generated by the SQLAlchemy default)
        merchant = Merchant(
            name=name,
            api_key=new_api_key,
            wallet_address=wallet_address
        )
        
        db.add(merchant)
        db.commit()
        db.refresh(merchant)
        
        print("\n" + "="*50)
        print("✅ SUCCESS: Merchant has been added.")
        print("="*50)
        print(f"Merchant ID : {merchant.id}")
        print(f"Name        : {merchant.name}")
        print(f"Wallet      : {merchant.wallet_address}")
        print("-" * 50)
        print(f"X-API-Key   : {new_api_key}")
        print("-" * 50)
        print("⚠️  CRITICAL: Store this key securely NOW!")
        print("This is the ONLY time it will be shown in plain text.")
        print("="*50 + "\n")
        
    except Exception as e:
        db.rollback()
        print(f"\n❌ FATAL: Failed to create merchant: {e}", file=sys.stderr)
        sys.exit(1)
    finally:
        db.close()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="SOLEPay Server - Secure Merchant Generator")
    parser.add_argument(
        "--name", 
        type=str, 
        required=True, 
        help="The name of the new merchant (e.g., 'Community Library')"
    )
    parser.add_argument(
        "--wallet",
        type=str,
        required=True,
        help="The merchant's SOLE wallet address (e.g., '1NXVc9JY9eVerzeqcvatMgHkrDYAJc2ec4')"
    )
    
    args = parser.parse_args()
    
    create_merchant(args.name, args.wallet)
